MyOwnUIProject/Controllers/BranchController.cs
using DTOs;
using Microsoft.AspNetCore.Mvc;
using ServicesContract;

namespace MyOwnUIProject.Controllers
{
    public class BranchController : Controller
    {
        private readonly IBranchService _branchService;

        public BranchController(IBranchService BranchService)
        {
            _branchService = BranchService;
        }

        [Route("/Branches")]
        public IActionResult Index()
        {
            var branches=_branchService.GetBranches();
            return View(branches);
        }

        [HttpGet]
        [Route("/Branches/Edit/{branchId:int}")]
        public IActionResult EditBranch(int branchId)
        {
            var branch = _branchService.GetBranchById(branchId);
            if (branch==null)
            {
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        [HttpPost]
        [Route("/Branches/Edit/{branchId:int}")]
        public IActionResult EditBranch(BranchDto model)
        {
            if (!ModelState.IsValid)
            {
                List<string> errors = new List<string>();

                foreach (var item in ModelState.Values)
                {
                    foreach (var error in item.Errors)
                    {
                        errors.Add(error.ErrorMessage);
                    }
                }
                ViewBag.Errors = errors;
                return View();
            }

            var branch = _branchService.GetBranchById(model.Id);
            if (branch==null)
            {
                return RedirectToAction("Index");
            }
            _branchService.UpdateBranch(model);
            return RedirectToAction("Index");
        }

        [Route("/Branches/Add")]
        public IActionResult AddBranch()
        {
            return View();
        }

        [Route("/Branches/Delete")]
        public IActionResult DeleteBranch()
        {
            return View();
        }

        [Route("/Branches/GetProducts/{branchId}")]
        public IActionResult GetProducts(int branchId)
        {
            var products = _branchService.GetProducts(branchId);
            var branch= _branchService.GetBranchById(branchId);
            ViewBag.Branch = branch.Name;

            return View(products);
        }
    }
}

MyOwnUIProject/Views/Shared/_Gridcolumn.cshtml
@using DTOs
@model DTOs.ColumnNameDto

@if (ViewBag.sortField == Model.ColumnName && ViewBag.orderBy == OrderEnum.ASC.ToString())
{
    <a href="~/products?searchType=@ViewBag.searchType&searchText=@ViewBag.searchText&sortField=@Model.ColumnName&orderBy=@OrderEnum.DESC">@Model.PersianName</a>
    <i class="bi bi-caret-down-fill"></i>

}
else if (ViewBag.sortField == Model.ColumnName && ViewBag.orderBy == OrderEnum.DESC.ToString())
{
    <a href="~/products?searchType=@ViewBag.searchType&searchText=@ViewBag.searchText&sortField=@Model.ColumnName&orderBy=@OrderEnum.ASC">@Model.PersianName</a>
    <i class="bi bi-caret-up-fill"></i>
}
else
{
    <a href="~/products?searchType=@ViewBag.searchType&searchText=@ViewBag.searchText&sortField=@Model.ColumnName&orderBy=@OrderEnum.ASC">@Model.PersianName</a>
    <i class="bi bi-caret-up-fill"></i>
}

MyOwnUIProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html dir="rtl">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="~/">صفحه اصلی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/products">محصولات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/products/create">ایجاد محصول</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Branch" asp-action="Index">لیست شعب</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">ثبت نام</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
<div>
    @RenderBody()

</div>
    <script asp-fallback-test="window.jQuery" asp-fallback-src="~/scripts/jquery.min.js" src="https://cdnjs.cloudflare.com/ajax/libs/jquery1/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/scripts/jquery.validate.min.js" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js" integrity="sha512-KFHXdr2oObHKI9w4Hv1XPKc898mE4kgYx58oqsc/JqqdLMDI4YjOLzom+EMlW8HFUd0QfjfAvxSL6sEq/a42fQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script asp-fallback-test="window.jQuery.validator.unobtrusive" asp-fallback-src="~/scripts/jquery.validate.unobtrusive.min.js" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>